<style type="text/css">
    .progress {
        margin-bottom: 2px;
    }
    .bar {
        text-overflow: visible;
    }
    
    .bar p {
        width: 100%;
    }
    .dataTables_filter {
        float: right;
        margin-top: -36px !important;
    }
</style>
<script type="text/javascript">
    $(document).ready(function(){
       $('a[data-toggle="tooltip"]').tooltip();
       $('#associationRules').dataTable(
        {
            "iDisplayLength": -1,
            "sDom": '<"top"f<"clear">>rt<"bottom"i<"clear">>'
        });
    });
</script>
<h4> - Number of Transactions: <?php echo $this->numberTransactions; ?></h4>
<h4> - Support Threshold: <?php echo $this->supportDesired . ' (' . $this->supportDesired*100 . '%)'?></h4>
<h4> - Minimum Support: <?php echo $this->minimumSupport; ?></h4>
<h4> - Minimum Confidence: <?php echo $this->minimumConfidence . ' (' . $this->minimumConfidence*100 . '%)'; ?></h4>

<hr/>
<?php
foreach($this->apriori as $level){
    echo $this->renderLevel($level);
}

echo $this->renderAssociationRules($this->associationRules, $this->minimumConfidence);

?>