<form action="<?php echo $this->url(array('controller' => 'apriori', 'action' => 'calculate'), null, true); ?>" method="post">
    <fieldset><br/>
        <legend>Apriori Calculation:</legend>
        <label>Desired Minimum Support Level:</label>
            <input type="text" placeholder="Default: .3" name="support"> 
        <label>Desired Minimum Confidence Level:</label>
            <input type="text" placeholder="Default: .75" name="minConfidence"> 
        <label>Data Set:</label>
            <select name="dataset">
                <option value="<?php echo SET_PREPROCESSED; ?>">Preprocessed</option>
                <option value="<?php echo SET_RAW; ?>">Raw Data</option>
            </select>
        <input type="submit" value="Calculate" class="btn btn-primary" style="margin-top:-8px;" />
    </fieldset>
    <fieldset><br/>
        <legend>Data:</legend>
        <label>Database: <?php echo $this->db->params->dbname; ?></label>
        <label>Raw Data:</label>
        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>Customer Number</th>
            <?php
            foreach($this->fields as $value){
                echo "<th>$value</th>";
            }
            ?>
            </tr>
            <?php
            foreach($this->data as $row){
                echo "<tr>";
                foreach($row as $value){
                    echo "<td>$value</td>";
                }
                echo "</tr>";
            }
            ?>
        </table>
    </fieldset>
</form>