<div class="container footer">
    <hr />
    <div class="row" style="font-size:9pt;font-style:italic;">
        <div class="span6">&copy; <?php echo date('o'); ?> Flying Sparx. All right reserved.</div>
        <div class="span6">
            <ul>
                <li><a href="#">Terms Of Service</a></li>
                <li><a href="#">Privacy</a></li>
            </ul>
        </div>
    </div>
</div>