<head>
    <meta charset="utf-8">   
    <title>Flying Sparx</title>
    <meta name="viewport" content="width=device-width, initial-scale=.8">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/css/style.css" rel="stylesheet">
    <link href="/assets/css/bs-roger.css" rel="stylesheet">
    <link href="/assets/css/icon-style.css" rel="stylesheet">
    <!--<link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">-->
    <link href="/assets/css/jquery.fancybox.css" rel="stylesheet">
    <link href="/assets/css/dataTables_bootstrap.css" rel="stylesheet">
    <link href="/assets/css/validationEngine.jquery.css" rel="stylesheet">
    <link rel="shortcut icon" href="assets/img/favicon.ico" type="image/x-icon">
    <link rel="icon" href="assets/img/favicon.ico" type="image/x-icon">

    <script type="text/javascript" src="/assets/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="/assets/js/bootstrap.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.mousewheel-3.0.6.pack.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.fancybox.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.lazyLoad.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.dataTables_bootstrap.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.validationEngine-en.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.validationEngine.js"></script>
    <script type="text/javascript" src="/assets/js/scripts.js"></script>
    <!--[if lt IE 9]>
        <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>