<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">   
        <title>Flying Sparx</title>
        <meta name="viewport" content="width=device-width, initial-scale=.7">
        <meta name="description" content="">
        <meta name="author" content="">

        <!--<link href="/assets/css/bootstrap.css" rel="stylesheet">
        <link href="/assets/css/style.css" rel="stylesheet">
        <link href="/assets/css/bs-roger.css" rel="stylesheet"> -->
        <link href="/assets/css/landing-bs.css" rel="stylesheet">
        <link href="/assets/css/landing.css" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel="stylesheet">


        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
        <link rel="icon" href="img/favicon.ico" type="image/x-icon">

        <script type="text/javascript" src="/assets/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="/assets/js/bootstrap.js"></script>

        <script type="text/javascript">
            
            $(document).ready(function(){
                
                $('.placeholder').each(function(){
                    $(this).attr('data-original', $(this).html());
                })
                
                $('.placeholder').prev().keyup(function(){
                    if($(this).val()!=''){
                        $(this).next().html('');
                    }
                    else{
                        $(this).next().html($(this).next().attr('data-original'));
                    }
                })
                
            })
            
        </script>

        <!--[if lt IE 9]>
        <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->  
    </head>
    <body class="landing">	
        
        		<?php
                        echo $this->layout()->content;
                        ?>

        
            </body>
</html>