<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>CISC 6930 - Data Mining Final Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <script src="../assets/js/jquery-1.91.min.js"></script>
    <link href="../assets/css/bootstrap-responsive.min.css" rel="stylesheet">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/apriori">Data Mining - Cross Selling</a>
          <div class="nav-collapse collapse">
<!--            <ul class="nav">
              <li class="active"><a href="/apriori">Apriori</a></li>
              <li class="active"><a href="/classifier">Naïve Bayes Classifier</a></li>
            </ul>-->
<?php $partial = array('navigation/top.phtml', 'default') ?>
<?php $this->navigation()->menu()->setPartial($partial) ?>
<?php echo $this->navigation()->menu()->render() ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->layout()->content; ?>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/js/bootstrap.min.js"></script>
    <script src="../assets/js/jquery.dataTables.min.js"></script>
  </body>
</html>
